/*
SQL for price history support:

create table if not exists public.price_history (
  id bigint generated by default as identity primary key,
  part_id bigint references public.inventory(id) on delete cascade,
  old_price numeric(10,2) not null,
  new_price numeric(10,2) not null,
  reason text,
  changed_at timestamptz not null default now(),
  changed_by text
);

alter table public.price_history enable row level security;

create policy "Allow public read access" on public.price_history
for select using (true);

create policy "Allow public insert access" on public.price_history
for insert with check (true);
*/
